### ISSUE TITLE
kind request: add more bits in README on how does it actually work

### ISSUE THREAD

**Issue by 62mkv** [dmikusa/tiny-health-checker#14]
Hi, dear Sir! Thank you so much for this tool! 

I came here thru the Paketo buildpack and it took quite a while to figure out how to actually make it work (my first Paketo experience, he he) 

May I ask to add a bit on the internals, I guess what it does is it produces some exit status that Docker then relies on in order to determine container health? 

Thank you once again for your great contribution!!

**Comment by dmikusa** [comment]
> May I ask to add a bit on the internals, I guess what it does is it produces some exit status that Docker then relies on in order to determine container health?

Primarily, it's this:

> The tiny health checker is a small binary that can only make HTTP requests to localhost. The port and path are configurable, but that's it. This is sufficient for health checks, but should be difficult to misuse if your container is compromised.

The exit status is performed the way that Docker expects, so this tool is really designed to support Docker's health check requirements.

The docs for that are here: https://docs.docker.com/engine/reference/builder/#healthcheck

Specifically:

```
The command's exit status indicates the health status of the container. The possible values are:

0: success - the container is healthy and ready for use
1: unhealthy - the container is not working correctly
2: reserved - do not use this exit code
```

So this tool will return 0 when successful (i.e. HTTP 2xx). Otherwise, it returns 1.
